#!/usr/bin/env python3

import os
from datetime import datetime
import winrt.windows.data.xml.dom as dom
import winrt.windows.ui.notifications as notifications


def notify(message: str):
    """Creates a Native Toast pn Windows

    Args:
        message (str): Toast Message
    """

    # appID of Task Scheduler
    appID = "Microsoft.AutoGenerated.{C1C6F8AC-40A3-0F5C-146F-65A9DC70BBB4}"

    # Create notifier
    nManager = notifications.ToastNotificationManager
    notifier = nManager.create_toast_notifier(appID)

    # Define your notification as string
    tString = f"""
  <toast launch="{appID}">
    <visual>
      <binding template="ToastGeneric">
        <text>Status of Running Get DNAC Device List</text>
        <text>{message}</text>
        <text placement="attribution">Notification via Visual Studio Code</text>
        <image placement="appLogoOverride" src="{os.path.abspath('assets/vscode-logo.png')}"/>
        <group>
          <subgroup>
              <text hint-style="captionSubtle" hint-align="left">{datetime.now().strftime('%b %d %Y %H:%M:%S')}</text>
          </subgroup>
        </group>
      </binding>
    </visual>
    <actions>
      <action
        content="Dismiss"
        arguments="dismiss"
        activationType="background"/>
    </actions>
  </toast>
"""

    # Convert notification to an XmlDocument
    xDoc = dom.XmlDocument()
    xDoc.load_xml(tString)

    # Display notification
    notifier.show(notifications.ToastNotification(xDoc))
